[project]
name = "django-tdd"
version = "0.1.0"
description = "Project to learn about how to use TDD with Django and UV as packet manager"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = []
